<a href="https://colab.research.google.com/github/mohammadmotiurrahman/mohammadmotiurrahman.github.io/blob/main/cse317_2/linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a.shape)

(3,)


In [ ]:
b = np.array([
                [1,2,3],
                [4,5,6]
            ])
print(b.shape)

(2, 3)


In [ ]:
c = np.array(
        [        
            [
                [1,2,3],
                [4,5,6]    
             ],
             [
                [10,20,30],
                [40,50,60]
             ]
        ]
        )
print(c.shape)

(2, 2, 3)


In [ ]:
#empty
e = np.empty([3])
print(e)
e = np.empty([3,4])
print(e)

[1. 1. 1.]
[[9.34256398e-312 3.16202013e-322 0.00000000e+000 0.00000000e+000]
 [1.20953760e-312 4.66465602e-033 6.34436439e-066 2.47088397e-056]
 [2.05907750e+184 7.16454622e-038 2.00365172e-076 7.69122430e+169]]


In [ ]:
z = np.zeros([2,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
o = np.ones([3,4])
print(o)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
r = np.random.rand(2,4)
print(r)

[[0.8178617  0.01393303 0.56238242 0.41862615]
 [0.08657204 0.09575793 0.71053215 0.63408467]]


In [ ]:
r = np.random.randint(10, size= (2,5))
print(r)

[[1 2 2 5 3]
 [9 3 3 7 0]]


vectors

In [ ]:
a = np.random.randint(1,5, size = (5))
b = np.random.randint(1,5, size = (5))
print(a)
print(b)

[3 1 4 3 2]
[3 3 4 1 1]


In [ ]:
c = a + b
print(c)

[6 4 8 4 3]


In [ ]:
c = a - b
print(c)

[ 0 -2  0  2  1]


In [ ]:
c = a * b
print(c)

[ 9  3 16  3  2]


In [ ]:
c = a / b
print(c)

[1.         0.33333333 1.         3.         2.        ]


In [ ]:
c = a.dot(b)
print(c)

33


In [ ]:
c = a * 2
print(c)

[6 2 8 6 4]


In [ ]:
m = np.random.randint(1,5, size=(3,3))
a = np.tril(m,-1)
print(a)

[[0 0 0]
 [4 0 0]
 [1 2 0]]


In [ ]:
m = np.random.randint(1,5, size=(3,3))
a = np.triu(m,1)
print(a)

[[0 3 2]
 [0 0 2]
 [0 0 0]]


In [ ]:
m = np.random.randint(1,5, size=(3,3))
print(m)
a = np.diag(m)
print(a)

[[2 1 4]
 [3 4 4]
 [3 3 3]]
[2 4 3]


In [ ]:
i = np.identity(3)
print(i)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#norm
a = np.random.randint(1,5, size = (3))
print(a)
print(np.linalg.norm(a))

[4 1 1]
4.242640687119285


In [ ]:
#matrix transpose
a = np.random.randint(1,5, size = (2,3))
print(a)
print(a.shape)
b = (a.T)
print(b)
print(b.shape)

[[2 2 4]
 [1 2 4]]
(2, 3)
[[2 1]
 [2 2]
 [4 4]]
(3, 2)


In [ ]:
#inverse of a matrix
a = np.random.randint(1,5, size = (3,3))
print(a)
b = np.linalg.inv(a)
print(b)

[[3 1 4]
 [2 2 3]
 [2 4 1]]
[[ 1.  -1.5  0.5]
 [-0.4  0.5  0.1]
 [-0.4  1.  -0.4]]


In [ ]:
#trace of a matrix
a = np.random.randint(1,5, size = (3,3))
print(a)
b = np.trace(a)
print(b)

[[1 1 1]
 [2 4 4]
 [2 2 4]]
9


In [ ]:
#determinant
a = np.random.randint(1,5, size = (3,3))
print(a)
b = np.linalg.det(a)
print(b)

[[3 1 2]
 [3 4 1]
 [4 3 2]]
-1.0000000000000002


In [ ]:
#rank
a = np.random.randint(1,5, size = (3,3))
print(a)
r = np.linalg.matrix_rank(a)
print(r)

[[3 1 3]
 [2 3 4]
 [3 3 2]]
3


In [ ]:
#qr??
a = np.random.randint(1,5, size = (3,3))
print(a)
Q, R = np.linalg.qr(a)
print(Q)
print(R)

[[4 2 4]
 [3 3 4]
 [3 1 4]]
[[-0.68599434  0.23606684 -0.6882472 ]
 [-0.51449576 -0.82623395  0.22941573]
 [-0.51449576  0.51147816  0.6882472 ]]
[[-5.83095189 -3.4299717  -6.85994341]
 [ 0.         -1.49509    -0.31475579]
 [ 0.          0.          0.91766294]]


In [ ]:
a = np.random.randint(1,5, size = (3,3))
val, vec = np.linalg.eig(a)
print(val)
print(vec)

[ 6.32246081 -2.45149727  0.12903646]
[[-0.40475024 -0.63079997  0.17949257]
 [-0.79411614 -0.12178298 -0.94773004]
 [-0.45338373  0.76632911  0.26379952]]


In [ ]:
import scipy as sc

In [ ]:
#lu decomposition
a = np.random.randint(1,5, size = (3,3))
P, L, U = sc.linalg.lu(a)
print(L)
print(U)
print(P)

[[1.         0.         0.        ]
 [1.         1.         0.        ]
 [0.66666667 0.         1.        ]]
[[ 3.          3.          2.        ]
 [ 0.          1.          0.        ]
 [ 0.          0.         -0.33333333]]
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
a = np.random.randint(1,5, size = (3,3))
U, S, V = sc.linalg.svd(a)
print(U)
print(S)
print(V)

[[-0.42009605 -0.86096706  0.28680138]
 [-0.57609898  0.49721122  0.6487611 ]
 [-0.7011628   0.10731599 -0.70487871]]
[9.00402925 2.17671482 1.47965194]
[[-0.48610962 -0.69006132 -0.53620221]
 [ 0.25851773 -0.69966473  0.66606145]
 [-0.83478502  0.1851611   0.51850684]]


In [ ]:
#mean
a = np.random.randint(1,5, size = (3,3))
m = np.mean(a)
print(m)

2.111111111111111


In [ ]:
#variance
a = np.random.randint(1,5, size = (3,3))
v = np.var(a)
print(v)

1.3580246913580245


In [ ]:
#std dev
a = np.random.randint(1,5, size = (3,3))
std_dev = np.std(a)
print(std_dev)

1.1653431646335017


In [ ]:
#covariance matrix
a = np.random.randint(1,5, size = (3,3))
b = np.random.randint(1,5, size = (3,3))
c = np.cov(a,b)
print(c)

[[ 1.33333333 -1.         -0.66666667 -0.33333333 -1.33333333 -1.        ]
 [-1.          3.         -1.         -0.5         2.5         0.        ]
 [-0.66666667 -1.          1.33333333  0.66666667 -0.33333333  1.        ]
 [-0.33333333 -0.5         0.66666667  0.33333333 -0.16666667  0.5       ]
 [-1.33333333  2.5        -0.33333333 -0.16666667  2.33333333  0.5       ]
 [-1.          0.          1.          0.5         0.5         1.        ]]


In [ ]:
#linear least square
a = np.random.randint(1,5, size = (3,3))
b = np.random.randint(1,5, size = (3,3))
l = np.linalg.lstsq(a,b)
print(l)

(array([[-1.        , -0.33333333,  2.        ],
       [ 5.5       ,  3.66666667, -6.5       ],
       [-2.        , -1.        ,  3.        ]]), array([], dtype=float64), 3, array([8.17773683, 2.65485302, 0.27636156]))


<ipython-input-90-eddb8ff1a82b>:4: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  l = np.linalg.lstsq(a,b)


https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.linalg.html

https://docs.scipy.org/doc/numpy-1.13.0/reference/routines.statistics.html

https://docs.scipy.org/doc/scipy/reference/tutorial/linalg.html#

https://github.com/scalanlp/breeze/wiki/Linear-Algebra-Cheat-Sheet